version: "3.8"
services:
  mongo:
    image: mongo:latest
    deploy:
      replicas: 1
    ports:
     - "27017:27017"
    networks:
     - mynetwork

  liveperson:
    build:
      context: ./
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    networks:
    - mynetwork

networks:
  mynetwork:
    external: true
    driver: overlay